import Foundation

/// Recently copied text, newest first. Kept in memory only: clipboards hold
/// passwords and other things that shouldn't be written to disk, so history
/// starts empty each time Hop launches.
public struct ClipboardHistory: Sendable {
    public struct Entry: Identifiable, Hashable, Sendable {
        public let id: UUID
        public let text: String
        public let copiedAt: Date
    }

    public private(set) var entries: [Entry] = []
    public let limit: Int
    /// Longer copies are skipped: a 5 MB log isn't something to paste from a list.
    public let maxLength: Int

    public init(limit: Int = 200, maxLength: Int = 100_000) {
        self.limit = limit
        self.maxLength = maxLength
    }

    /// Adds a copy. Copying something already in the list moves it to the top
    /// instead of adding it twice.
    public mutating func add(_ text: String, at date: Date = .now) {
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty, text.count <= maxLength else { return }
        entries.removeAll { $0.text == text }
        entries.insert(Entry(id: UUID(), text: text, copiedAt: date), at: 0)
        if entries.count > limit { entries.removeLast(entries.count - limit) }
    }

    public mutating func remove(_ id: UUID) {
        entries.removeAll { $0.id == id }
    }

    public mutating func clear() {
        entries.removeAll()
    }

    /// Entries containing every word of the query, newest first.
    public func search(_ query: String) -> [Entry] {
        let words = query.lowercased().split(separator: " ")
        guard !words.isEmpty else { return entries }
        return entries.filter { entry in
            let text = entry.text.lowercased()
            return words.allSatisfy { text.contains($0) }
        }
    }

    /// Pasteboard types that password managers and other apps use to say
    /// "don't keep this" (see nspasteboard.org). Copies carrying any of them
    /// are never added.
    public static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]
}
